// Section registry + the single computation pipeline. Modules are pure and
// synchronous, so this runs identically in the browser (live reflow) and in
// scripts/tests. The executive summary always computes LAST so it can read
// every other section's rangedFigures and headline stats.

import type {
  CompanyProfile,
  ProposalContext,
  ScenarioAssumptions,
  SectionConfigEntry,
  SectionKind,
  SectionOutput,
  UseCase,
  ValueModelInputs,
} from "@/lib/types";
import { DEFAULT_VALUE_MODEL } from "@/lib/data/defaults";
import { problemSection } from "./problem";
import { businessValueSection } from "./business-value";
import { costSection } from "./cost";
import { currentStateSection } from "./current-state";
import { futureStateSection } from "./future-state";
import { productSection } from "./product";
import { useCasePersonaSection } from "./use-case-persona";
import { proposalSection } from "./proposal";
import { forecastSection } from "./forecast";
import { roadmapSection } from "./roadmap";
import { nextStepsSection } from "./next-steps";
import { executiveSummarySection } from "./executive-summary";
import { peerProofSection } from "./peer-proof";
import { applyBaseScenario } from "./scenario";

/** Default display ordering — executive-deck flow: story first, asks, then
 *  the scenario/cost detail as appendix material (the exporter inserts a
 *  divider before the trailing appendix kinds). */
export const DEFAULT_SECTION_ORDER: SectionKind[] = [
  "executive_summary",
  "problem",
  "current_state",
  "future_state",
  "product",
  "use_case_persona",
  "peer_proof",
  "business_value",
  "proposal",
  "roadmap",
  "next_steps",
  "forecast",
  "cost",
];

/** Kinds that read as appendix detail when they trail the deck. */
export const APPENDIX_KINDS: ReadonlySet<SectionKind> = new Set([
  "forecast",
  "cost",
]);

/** Preview (readout) sequence — a CFO readout leads with the answer: value,
 *  then where it comes from, then cost, then break-even, then the ask, then the
 *  supporting narrative. ONLY the Preview slideshow re-sequences; the Build
 *  screen keeps raw DEFAULT_SECTION_ORDER. Opens on executive_summary. */
export const READOUT_ORDER: SectionKind[] = [
  "executive_summary", // the answer / headline value
  "peer_proof", // social proof up front (omitted when no relevant peer)
  "business_value", // where the value comes from (drivers)
  "proposal", // value tied to demand + the asks
  "cost", // what it costs
  "forecast", // trajectory + break-even
  "roadmap", // how we get there
  "next_steps", // the ask
  "problem", // supporting narrative ↓
  "current_state",
  "future_state",
  "product",
  "use_case_persona",
];

/** Synchronous module signature used by the registry. The public
 *  SectionModule type allows Promise for future async modules; everything in
 *  v1 is sync so live reflow stays a plain useMemo. */
// Modules may return null to OMIT themselves (e.g. peer_proof when no relevant
// customer story is found) — computeAllSections skips nulls.
type SyncSectionModule = (ctx: ProposalContext) => SectionOutput | null;

// Partial: the synthetic scenario kinds (scenario_conservative/_upside) have no
// module — they're generated by lib/sections/scenario.ts, not computed here.
const SECTION_MODULES: Partial<Record<SectionKind, SyncSectionModule>> = {
  executive_summary: executiveSummarySection,
  problem: problemSection,
  current_state: currentStateSection,
  future_state: futureStateSection,
  product: productSection,
  use_case_persona: useCasePersonaSection,
  peer_proof: peerProofSection,
  business_value: businessValueSection,
  proposal: proposalSection,
  cost: costSection,
  forecast: forecastSection,
  roadmap: roadmapSection,
  next_steps: nextStepsSection,
};

/** Dependency-safe computation order: content sections first (economic trio
 *  before sections that reference their figures), exec summary last. */
const COMPUTE_ORDER: SectionKind[] = [
  "problem",
  "current_state",
  "future_state",
  "product",
  "use_case_persona",
  "peer_proof",
  "business_value",
  "cost",
  "forecast",
  "proposal",
  "roadmap",
  "next_steps",
  "executive_summary",
];

export interface ProposalInputs {
  company: CompanyProfile;
  assumptions: ScenarioAssumptions;
  selectedUseCases: UseCase[];
  /** Inputs for the top_down value approach. Optional — callers that only
   *  exercise the default bottom_up path (scripts, pre-feature saved payloads)
   *  may omit it. */
  valueModel?: ValueModelInputs;
  sectionConfig: SectionConfigEntry[];
}

export function defaultSectionConfig(): SectionConfigEntry[] {
  return DEFAULT_SECTION_ORDER.map((kind, i) => ({
    kind,
    order: i,
    enabled: true,
    // Forecast + Cost start in the appendix lane (the prior default behavior);
    // the user can drag them above the appendix divider on the Build screen.
    appendix: APPENDIX_KINDS.has(kind),
  }));
}

/**
 * Reconciles persisted configuration with the current registry. Existing user
 * ordering and enablement win; newly introduced sections are appended with
 * their current defaults so older proposals never silently lose new content.
 */
export function normalizeSectionConfig(
  config?: readonly SectionConfigEntry[] | null,
): SectionConfigEntry[] {
  const defaults = defaultSectionConfig();
  if (!config?.length) return defaults;

  const knownKinds = new Set(DEFAULT_SECTION_ORDER);
  const seen = new Set<SectionKind>();
  const normalized: SectionConfigEntry[] = [];

  for (const entry of [...config].sort((a, b) => a.order - b.order)) {
    if (!knownKinds.has(entry.kind) || seen.has(entry.kind)) continue;
    seen.add(entry.kind);
    normalized.push({
      kind: entry.kind,
      order: normalized.length,
      enabled: entry.enabled,
      appendix: entry.appendix ?? APPENDIX_KINDS.has(entry.kind),
    });
  }

  for (const entry of defaults) {
    if (seen.has(entry.kind)) continue;
    normalized.push({ ...entry, order: normalized.length });
  }

  return normalized;
}

/**
 * Runs every registered module in dependency order, accumulating
 * priorSections, then stamps order/enabled from sectionConfig. Disabled
 * sections are still COMPUTED (their rangedFigures stay available to the
 * exec summary) — rendering and export filter on `enabled`.
 *
 * Returns sections sorted by configured order.
 */
export function computeAllSections(inputs: ProposalInputs): SectionOutput[] {
  const priorSections: ProposalContext["priorSections"] = {};
  const ctx: ProposalContext = {
    company: inputs.company,
    assumptions: inputs.assumptions,
    selectedUseCases: inputs.selectedUseCases,
    valueModel: inputs.valueModel ?? DEFAULT_VALUE_MODEL,
    priorSections,
  };

  const normalizedConfig = normalizeSectionConfig(inputs.sectionConfig);
  const configByKind = new Map(normalizedConfig.map((c) => [c.kind, c]));
  const outputs: SectionOutput[] = [];

  for (const kind of COMPUTE_ORDER) {
    const module = SECTION_MODULES[kind];
    const config = configByKind.get(kind);
    if (!module || !config) continue;

    const output = module(ctx);
    if (!output) continue; // module opted to omit itself (e.g. peer_proof, no match)
    output.order = config.order;
    output.enabled = config.enabled;
    output.appendix = config.appendix ?? false;
    priorSections[kind] = output;
    outputs.push(output);
  }

  // Display scenario (Part 4): the Executive Summary carries the full
  // conservative/base/optimistic range; every other slide shows ONLY the base
  // case (range data stays in rangedFigures, relocated to the scenario appendix
  // slides). This is a pure display change — rangedFigures are untouched.
  for (const s of outputs) {
    // Exec summary keeps the full range; peer_proof has its own provenance nugget
    // and no ranged figures — neither takes the "Base case" treatment.
    if (s.kind === "executive_summary" || s.kind === "peer_proof") continue;
    applyBaseScenario(s);
    s.scenarioTag = "Base case";
  }

  assertSerializable(outputs);
  return outputs.sort((a, b) => a.order - b.order);
}

/** Dev-only wire-format guard: SectionOutput crosses JSON three times (web
 *  state, /api/pptx body, jsonb column). NaN/Infinity stringify to null and
 *  silently corrupt charts — fail loudly here instead. */
function assertSerializable(outputs: SectionOutput[]): void {
  if (process.env.NODE_ENV === "production") return;
  if (JSON.stringify(outputs, jsonNumberGuard).includes("__NON_FINITE__")) {
    throw new Error("SectionOutput contains NaN/Infinity — check engine division paths");
  }
}

function jsonNumberGuard(_key: string, value: unknown): unknown {
  if (typeof value === "number" && !Number.isFinite(value)) {
    return "__NON_FINITE__";
  }
  return value;
}
